# Generated by Django 4.1.3 on 2022-11-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siposyandu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siposyandu',
            name='bb',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='siposyandu',
            name='tb',
            field=models.IntegerField(),
        ),
    ]
